name: Expo CI

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    env:
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm install

      - name: Install EAS CLI
        run: npm install -g eas-cli

      # - name: Expo EAS Update
      #   run: eas update --branch release --message "Update from GitHub Actions"

      - name: Expo EAS Update
        run: eas update --branch release --channel release --message "${{ github.event.head_commit.message }}"
